# Generated by Django 3.0.8 on 2020-08-11 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(default='', max_length=50)),
                ('text2', models.CharField(default='', max_length=50)),
                ('message1', models.CharField(default='', max_length=100)),
                ('message2', models.CharField(default='', max_length=100)),
                ('image_url1', models.URLField(default='', max_length=1000)),
                ('image_url2', models.URLField(default='', max_length=1000)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'detail_info',
            },
        ),
    ]
